FROM node:10
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG APP_PUBLIC_URL
ARG MAIL_FROM_ADDRESS
ARG MYSQL_DATABASE_URL
ARG PORT
ARG S3_ACCESS_KEY_ID
ARG S3_ACCESS_SECRET_KEY
ARG S3_BUCKET_NAME
ARG S3_BUCKET_REGION
ARG SES_PORT
ARG SES_SERVER_NAME
ARG SES_SMTP_LOGIN
ARG SES_SMTP_PASSWORD
RUN ./bin/create-config
CMD ["npm", "start", "--production"]
